# Generated by Django 4.2.28 on 2026-02-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrequest",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
